version: "3.3"

volumes:
  pkg:

services:

  goat:
    build: .
    volumes:
      - ./:/go/src/goat
    working_dir: /go/src/goat

  test:
    command: go test . -cover
    build: .
    volumes:
      - ./:/go/src/goat
    working_dir: /go/src/goat
    environment:
      APP_BASE: /go/src/goat
