networks:
  default:
    name: docker-dev
    external: true

volumes:
  pkg:
  db-volume:
  goat:

services:
  app:
    image: cli:dev
    volumes:
    - pkg:/go/pkg
    - ./:/app
    - ../../:/goat
    working_dir: /app/src

